# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d582f79def367159bf33d3445376407dabf440cc40b3bfd67d6d4b9b7a613ade9b6a6699d5ac8e4791d6fb74626ca4b4c775e650ab84c9721a6de32546567863

test:
  secret_key_base: 937f6f24a178c241b682b04ccad299d944a4ac965bdcb96ef64381e3020c0a589d025e1e65a799b12ba853fe76d5c0912ccdf4c4225e542afabb442f658f60e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
